{{$PROMETHEUS_SCRAPE_CILIUM_AGENT := DefaultParam .CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT false}}
{{$PROMETHEUS_SCRAPE_CILIUM_AGENT_PORT := DefaultParam .CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT_PORT "prometheus"}}
{{$PROMETHEUS_SCRAPE_CILIUM_AGENT_INTERVAL := DefaultParam .CL2_PROMETHEUS_SCRAPE_CILIUM_AGENT_INTERVAL "30s"}}

{{if $PROMETHEUS_SCRAPE_CILIUM_AGENT }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: cilium-service
  name: cilium-service
  namespace: monitoring
spec:
  endpoints:
    - interval: {{ $PROMETHEUS_SCRAPE_CILIUM_AGENT_INTERVAL }}
      port: http-metrics
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: cilium-service
{{end}}
