apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    k8s-app: dns-client-pods
  name: dns-client-pods
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - interval: 5s
      port: dnsperfmetrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      testlabel: testing
  namespaceSelector:
    any: true
