apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Name}}
data:
  all-queries: |
      my-bucket.s3.us-west-2.amazonaws.com
      other-bucket.s3.us-west-2.amazonaws.com
      xxx.s3.us-west-2.amazonaws.com
      yyy.s3.us-west-2.amazonaws.com
      www.s3.us-west-2.amazonaws.com
      zzz.s3.us-west-2.amazonaws.com