name: node-throughput
namespace:
  number: 1
tuningSets:
- name: default
  qpsLoad:
    qps: 1
steps:
- name: Create configmap
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: dns-prober
      objectTemplatePath: configmap.yaml

- name: Starting measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDaemonSets
      Params:
        apiVersion: apps/v1
        kind: DaemonSet
    Params:
      action: start
      labelSelector: group = load
      operationTimeout: 2m

- name: Create Daemonset that performs DNS requests
  phases:
  - namespaceRange:
      min: 1
      max: 1
    replicasPerNamespace: 1
    tuningSet: default
    objectBundle:
    - basename: dns-prober
      objectTemplatePath: dns-prober.yaml

- name: Starting measurement
  measurements:
  - Method: WaitForControlledPodsRunning
    Instances:
    - Identifier: WaitForRunningDaemonSets
      Params:
        apiVersion: apps/v1
        kind: DaemonSet
    Params:
      action: gather
      labelSelector: group = load
      operationTimeout: 2m

- name: "Starting measurements"
  measurements:
  - Identifier: DNSPerformanceMetrics
    Method: GenericPrometheusQuery
    Params:
      action: start
      metricName: DNS Performance
      metricVersion: v1
      unit: s
      queries:
      - name: DNS Error Percentage
        query: sum(increase(dns_errors_total[%v])) / sum(increase(dns_lookups_total[%v])) * 100
      - name: DNS Lookup Latency - Perc50
        query: histogram_quantile(0.5, sum(rate(dns_lookup_latency_bucket[%v])) by (le))
      - name: DNS Lookup Latency - Perc99
        query: histogram_quantile(0.99, sum(rate(dns_lookup_latency_bucket[%v])) by (le))

- name: Sleep
  measurements:
  - Identifier: WaitAfterExec
    Method: Sleep
    Params:
      duration: 60s

- name: "Gathering measurements"
  measurements:
  - Identifier: DNSPerformanceMetrics
    Method: GenericPrometheusQuery
    Params:
      action: gather
      metricName: DNS Performance
      metricVersion: v1
      unit: s
      queries:
      - name: DNS Error Percentage
        query: sum(increase(dns_errors_total[%v])) / sum(increase(dns_lookups_total[%v])) * 100
      - name: DNS Lookup Latency - Perc50
        query: histogram_quantile(0.5, sum(rate(dns_lookup_latency_bucket[%v])) by (le))
      - name: DNS Lookup Latency - Perc99
        query: histogram_quantile(0.99, sum(rate(dns_lookup_latency_bucket[%v])) by (le))
